### ISSUE TITLE
Mapping.js and Mongoose Mixed type

### ISSUE THREAD

**Issue by nodkz** [jbdemonte/mongoose-elasticsearch-xp#17]
According to
https://github.com/jbdemonte/mongoose-elasticsearch-xp/blame/master/lib/mapping.js#L96 `mixed` type (`mongoose.Schema.Types.Mixed`) considered as embedded schema, but it does not contain `paths` key and looks like:
```js 
descriptionRaw Mixed {
      path: 'descriptionRaw',
      instance: 'Mixed',
      validators: [],
      setters: [],
      getters: [ [Function: get] ],
      options:
       { type: { [Function: Mixed] schemaName: 'Mixed' },
         get: [Function: get] },
      _index: null }
```

If I save doc with such field I got such error:
```
TypeError: Cannot read property 'paths' of undefined
    at generate (/Users/nod/www/rabota/lib/mongoose-elasticsearch-xp/lib/mapping.js:19:21)
    at /Users/nod/www/rabota/lib/mongoose-elasticsearch-xp/lib/mapping.js:65:32
    at Array.forEach (native)
    at generate (/Users/nod/www/rabota/lib/mongoose-elasticsearch-xp/lib/mapping.js:19:29)
    at /Users/nod/www/rabota/lib/mongoose-elasticsearch-xp/lib/mapping.js:65:32
    at Array.forEach (native)
    at generate (/Users/nod/www/rabota/lib/mongoose-elasticsearch-xp/lib/mapping.js:19:29)
    at model.esOptions (/Users/nod/www/rabota/lib/mongoose-elasticsearch-xp/index.js:42:21)
    at model.postSave (/Users/nod/www/rabota/lib/mongoose-elasticsearch-xp/index.js:526:25)

    at Function.<anonymous> (/Users/nod/www/rabota/node_modules/mongoose/lib/schema.js:1109:17)
    at emitTwo (events.js:106:13)
    at Function.emit (events.js:191:7)
    at /Users/nod/www/rabota/node_modules/mongoose/lib/model.js:268:23
    at /Users/nod/www/rabota/node_modules/mongoose/lib/model.js:155:7
    at /Users/nod/www/rabota/node_modules/mongodb/lib/collection.js:525:5
    at /Users/nod/www/rabota/node_modules/mongodb/lib/collection.js:703:5
    at handleCallback (/Users/nod/www/rabota/node_modules/mongodb/lib/utils.js:95:56)
    at /Users/nod/www/rabota/node_modules/mongodb/lib/bulk/unordered.js:465:9
    at handleCallback (/Users/nod/www/rabota/node_modules/mongodb/lib/utils.js:95:56)
    at resultHandler (/Users/nod/www/rabota/node_modules/mongodb/lib/bulk/unordered.js:413:5)
    at /Users/nod/www/rabota/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Should be `mixed` be removed? Or I something missing?

Without it all tests for ES2 and ES5 are passed.

**Comment by jbdemonte** [comment]
I'll have to check deeper this change, because, when I did it, I haven't this kind of problem, and It's not impossible that we use it in my company

**Comment by nodkz** [comment]
Already in master https://github.com/jbdemonte/mongoose-elasticsearch-xp/blob/master/lib/mapping.js#L108
