### ISSUE TITLE
TypeError: _Promise is not a constructor

### ISSUE THREAD

**Issue by nondefyde** [jbdemonte/mongoose-elasticsearch-xp#36]
TypeError: _Promise is not a constructor
    at Object.module.exports.run (C:\Users\Emmanuel\WebstormProjects\majobs-webservice\node_modules\mongoose-elasticsearch-xp\lib\utils.js:30:12)
    at Function.synchronize [as esSynchronize] (C:\Users\Emmanuel\WebstormProjects\majobs-webservice\node_modules\mongoose-elasticsearch-xp\lib\index.js:327:16)
    at Object.<anonymous> (C:/Users/Emmanuel/WebstormProjects/majobs-webservice/src/models/job.js:348:5)
    at Module._compile (module.js:569:30)
    at loader (C:\Users\Emmanuel\WebstormProjects\majobs-webservice\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Emmanuel\WebstormProjects\majobs-webservice\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:/Users/Emmanuel/WebstormProjects/majobs-webservice/src/lang/en/job.js:1:1)
    at Module._compile (module.js:569:30)
    at loader (C:\Users\Emmanuel\WebstormProjects\majobs-webservice\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Emmanuel\WebstormProjects\majobs-webservice\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at _underscore2.default.each.file (C:/Users/Emmanuel/WebstormProjects/majobs-webservice/src/lang/index.js:17:12)
    at Function._.each._.forEach (C:\Users\Emmanuel\WebstormProjects\majobs-webservice\node_modules\underscore\underscore.js:153:9)
    at Object.<anonymous> (C:/Users/Emmanuel/WebstormProjects/majobs-webservice/src/lang/index.js:16:3)
    at Module._compile (module.js:569:30)
    at loader (C:\Users\Emmanuel\WebstormProjects\majobs-webservice\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Emmanuel\WebstormProjects\majobs-webservice\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by nodkz** [comment]
Fixed in #38
This problem was with mongoose 5.0.0, not elasticsearch.
