### ISSUE TITLE
Does not seem to work with ES v5.x

### ISSUE THREAD

**Issue by jeremythille** [jbdemonte/mongoose-elasticsearch-xp#9]
Works with ElasticSearch 2.4, does not after upgrading to ES v5.x.

`Model.esCreateMapping()` gives the following error : 

```
Elasticsearch DEBUG: 2017-01-23T16:08:18Z
  starting request { method: 'POST', path: '/ads', body: {}, query: {} }


Elasticsearch TRACE: 2017-01-23T16:08:18Z
  -> POST http://localhost:9200/ads
  {}
  <- 400
  No handler found for uri [/ads] and method [POST]

Elasticsearch DEBUG: 2017-01-23T16:08:18Z
  Request complete

esCreateMapping error : { Error: Bad Request
    at respond (/www/dev/toven/admin/node_modules/elasticsearch/src/lib/transport.js:293:15)
    at checkRespForFailure (/www/dev/toven/admin/node_modules/elasticsearch/src/lib/transport.js:252:7)
    at HttpConnector.<anonymous> (/www/dev/toven/admin/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
    at IncomingMessage.wrapper (/www/dev/toven/admin/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  status: 400,
  displayName: 'BadRequest',
  message: 'Bad Request' }

```

**Comment by jbdemonte** [comment]
Latest version should fix this problem,
Let me know if it's ok
